export const theme = {
  colors: {
    background: '#f4f6f8',
    backgroundSoft: '#f9fafb',
    panel: '#ffffff',
    panelStrong: '#ffffff',
    panelMuted: '#f9fafb',
    text: '#111827',
    muted: '#667085',
    accent: '#1d4ed8',
    accentSoft: '#dbeafe',
    accentWarm: '#d97706',
    accentWarmSoft: '#fef3c7',
    success: '#15803d',
    successSoft: '#dcfce7',
    warning: '#d97706',
    warningSoft: '#fef3c7',
    danger: '#dc2626',
    dangerSoft: '#fee2e2',
    border: '#d9dee7',
    borderSoft: '#edf0f5',
    white: '#ffffff',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 4,
    md: 6,
    lg: 8,
    pill: 999,
  },
};
